config/routes.rb
TwitterClone::Application.routes.draw do

  root :to => "users#home"

  match 'user/edit' => 'users#edit', :as => :edit_current_user

  match 'signup' => 'users#new', :as => :signup

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'login' => 'sessions#new', :as => :login

  resources :sessions

  resources :users do
    collection do
      get :home
    end
    member do
      post :tweet
    end
  end

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user
  
  validates_presence_of :user
  validates_presence_of :text
  validates_length_of :text, :maximum => 140, :allow_blank => false

  default_scope order('created_at DESC').includes(:user)
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :tweets

  # new columns need to be added here to be writable through mass assignment
  attr_accessible :username, :email, :password, :password_confirmation

  attr_accessor :password
  before_save :prepare_password

  validates_presence_of :username
  validates_uniqueness_of :username, :email, :allow_blank => true
  validates_format_of :username, :with => /^[-\w\._@]+$/i, :allow_blank => true, :message => "should only contain letters, numbers, or .-_@"
  validates_format_of :email, :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i
  validates_presence_of :password, :on => :create
  validates_confirmation_of :password
  validates_length_of :password, :minimum => 4, :allow_blank => true

  # login can be either username or email address
  def self.authenticate(login, pass)
    user = find_by_username(login) || find_by_email(login)
    return user if user && user.matching_password?(pass)
  end

  def matching_password?(pass)
    self.password_hash == encrypt_password(pass)
  end

  private

  def prepare_password
    unless password.blank?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = encrypt_password(password)
    end
  end

  def encrypt_password(pass)
    BCrypt::Engine.hash_secret(pass, password_salt)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ControllerAuthentication
  protect_from_forgery
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.authenticate(params[:login], params[:password])
    if user
      session[:user_id] = user.id
      flash[:notice] = "Logged in successfully."
      redirect_to_target_or_default("/")
    else
      flash.now[:error] = "Invalid login or password."
      render :action => 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You have been logged out."
    redirect_to "/"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :login_required, :except => [:new, :create, :show]

  def home
    @tweets = Tweet.paginate(:per_page => 20, :page => params[:page])
    @tweet = Tweet.new
  end

  def show
    @user = User.find(params[:id])
    @tweets = @user.tweets.paginate(:per_page => 20, :page => params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Thank you for signing up! You are now logged in."
      redirect_to "/"
    else
      render :action => 'new'
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update_attributes(params[:user])
      flash[:notice] = "Your profile has been updated."
      redirect_to "/"
    else
      render :action => 'edit'
    end
  end

  def tweet
    tweet = Tweet.new(:user => current_user, :text => params[:tweet][:text])
    flash[:notice] = "Tweet posted." if tweet.valid?
    render :text => tweet.save
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_url(user)
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    "http://gravatar.com/avatar/#{gravatar_id}.png?s=48"
  end
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= "Invalid Fields"
    options[:message] ||= "Correct the following errors and try again."
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "TwitterClone" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
      <%- if logged_in? %>
        <div id="header">
          <%= link_to "Home", root_path, :title => "Home" %>
          |
          <%= link_to "Edit profile", edit_user_path(current_user), :title => "Edit profile" %>
          |
          <%= link_to "Logout", logout_path, :title => "Logout" %>
        </div>
      <% end %>
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
    <%= javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.min.js" %>
    <%= javascript_include_tag :defaults %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </p>
  <p>
    <%= f.label :email, "Email Address" %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation, "Confirm Password" %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p><%= f.submit (@user.new_record? ? "Sign up" : "Update") %></p>
<% end %>

app/views/users/_tweets_list.html.erb
<ul id="tweet_list">
  <%- @tweets.each do |tweet| %>
    <li>
      <%- user = tweet.user %>
      <%= link_to user, :title => user.username  do %>
        <%= image_tag gravatar_url(user) %>
      <% end %>
      <%= tweet.text %>
      <span class="time">
        <%= time_ago_in_words tweet.created_at %> ago
      </span>
    </li>
  <% end %>
</ul>

<%= will_paginate @tweets %>

app/views/users/edit.html.erb
<% title "Update Profile" %>

<%= render 'form' %>

app/views/users/home.html.erb
<% title "Home" %>
<h2>
  What are you doing?
</h2>
<div id="tweet">
  <%= form_for(@tweet, :url => tweet_user_path(current_user)) do |f| %>
    <%= f.text_area :text, :rows => 3, :cols => 110 %>
    <span id="tweet_length">
      140
    </span>
    <%= submit_tag "Tweet", :id => "tweet_this" %>
  <% end %>
</div>
<%= render :partial => "tweets_list" %>

app/views/users/new.html.erb
<% title "Sign up" %>

<p>Already have an account? <%= link_to "Log in", login_path %>.</p>

<%= render 'form' %>

app/views/users/show.html.erb
<% title @user.username %>
<%= render :partial => "tweets_list" %>